### ISSUE TITLE
Addon Aspects not Registering Properly, Nonexistent in Items but Existent in Infusion Recipes

### ISSUE THREAD

**Issue by prodzpod** [Zoko061602/planar-artifice#3]
The aspects in PAAspects.java doesn't seem to register properly. Items don't have the needed aspects, [Thaumic JEI](https://www.curseforge.com/minecraft/mc-mods/thaumic-jei) doesn't pick up on them, but it's somehow in the Infusion recipe. considering other addons - or even the 0.13 version works perfectly normally- I think its caused as a byproduct of your code cleanup.

Thanks a lot for continuing this mod. literally been looking for it for [months](https://www.reddit.com/r/feedthebeast/comments/ghgbpe/planar_artifice/).
I'm looking into this issue for myself as well, but I can't seem to figure out what's causing this issue. possibly something with Thaumcraft's API?

**Comment by Zoko061602** [comment]
Looks like I registered them in the wrong place, I moved them to postInit instead of the IRecipe Event.

**Comment by prodzpod** [comment]
Thaumic Additions being signed gave me an absolute business testing and somehow crashing because of it. anyways, checked and it works. Thanks for the quick fix.

**Comment by Sunconure11** [comment]
I’m still seeing this to an extent. Perhaps check the code of Bewitchment, to see how I’m registering my new aspects?
