### ISSUE TITLE
Fatal crash at startup

### ISSUE THREAD

**Issue by Yorick1234** [Zoko061602/planar-artifice#84]
**Describe the bug**
MineCraft fails to start

**To Reproduce**
1. Have my modlist and starting it.

**Expected behavior**
While launching my instance, there is a fatal sartup error, in which the game tells me that this mod (Planar Artifice: continuation) is identified as the cause of these troubles. I have tried versions 1.4.0-pre4 and -pre7

**Additional context**
See my 
[latest.log](https://github.com/Zokonius/planar-artifice/files/8169165/latest.log)
[debug.log](https://github.com/Zokonius/planar-artifice/files/8169167/debug.log)
[crash-2022-03-02_12.18.44-client.txt](https://github.com/Zokonius/planar-artifice/files/8169178/crash-2022-03-02_12.18.44-client.txt)

I read in this issues list (an issue from six days earlier) someone else had probably the same issue, and was asked about magicbees: I have that mod as well (v.3.2.25): no single config was changed (in my entire modlist whatsoever for the time being; all is default).

Could this be fixed, or could I be pointed out a correct working version of this excellent mod, to be capable of starting up my client? Thank you in advance for any response, and all your hard works in this mod, in all cases! There isn't much free in the world, you know, apart from mods. I cannot explain my gratitude towards such initiatives. A warm hearted cheers.

**Comment by Yorick1234** [comment]
I have made my modpack work with a different version: 1.3.4 (marked as release-version on CurseForge), which is fine for me!
Still, I have this bug report, rather for your reference, as I am sure others will face these troubles aswell using your later builds from past days (which are marked as release versions instead of alpha versions on CurseForge).

**Comment by prodzpod** [comment]
have you tried the newest version, this is not bc of magicbees but rather because of the newest thaumic additions version
